# Generated by Codex on 2026-03-19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_conversation_user_delete_chatlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('language', models.CharField(default='te-IN', max_length=20)),
                ('channel', models.CharField(default='voice', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('last_asr_confidence', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to='home.userprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('message_text', models.TextField()),
                ('normalized_text', models.TextField(blank=True, default='')),
                ('source', models.CharField(default='text', max_length=20)),
                ('language', models.CharField(default='te-IN', max_length=20)),
                ('asr_confidence', models.FloatField(blank=True, null=True)),
                ('intent', models.CharField(blank=True, default='', max_length=50)),
                ('extracted_parameters', models.JSONField(blank=True, default=dict)),
                ('predicted_crop', models.CharField(blank=True, default='', max_length=120)),
                ('model_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='home.voiceconversationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
